In [1]:
import os
import pandas as pd
import numpy as np
import pickle
from tqdm.notebook import tqdm

In [2]:
def load_pickle(path): 

    with open(path, "rb") as f: 
        return pickle.load(f)

def pickle_data(data, path):

    with open(path, "wb") as f:
        pickle.dump(data, f)

In [3]:
cleaned_labels = pd.read_excel("../../data/TCGA/clinical/TCGA-CDR-SupplementalTableS1.xlsx")

In [4]:
OS_labels = cleaned_labels[["bcr_patient_barcode", "OS", "OS.time"]]

In [5]:
PFS_labels = pd.read_excel("../../data/TCGA/clinical/TCGA-CDR-SupplementalTableS1.xlsx", sheet_name='ExtraEndpoints')

In [6]:
PFS_labels = PFS_labels[["bcr_patient_barcode", "PFS", "PFS.time"]]

In [7]:
# Merge the two dataframes on the 'bcr_patient_barcode' column
survival_labels = pd.merge(OS_labels, PFS_labels, on='bcr_patient_barcode', how='outer')

In [8]:
rename_cols = {
    "OS": "OS_event",
    "OS.time": "OS_time",
    "PFS": "PFS_event",
    "PFS.time": "PFS_time"
}

In [9]:
survival_labels.rename(columns=rename_cols, inplace=True)

In [10]:
survival_labels.head()

  bcr_patient_barcode  OS_event  OS_time  PFS_event  PFS_time
0        TCGA-02-0001       1.0    358.0        1.0     137.0
1        TCGA-02-0003       1.0    144.0        1.0      40.0
2        TCGA-02-0004       1.0    345.0        1.0     314.0
3        TCGA-02-0006       1.0    558.0        1.0     302.0
4        TCGA-02-0007       1.0    705.0        1.0     518.0

In [11]:
survival_labels.to_csv("../../data/TCGA/clinical/cleaned_survival_labels.csv", index=False)

In [12]:
survival_labels = pd.read_csv("../../data/TCGA/clinical/cleaned_survival_labels.csv")

In [14]:
survival_labels.head()

  bcr_patient_barcode  OS_event  OS_time  PFS_event  PFS_time
0        TCGA-02-0001       1.0    358.0        1.0     137.0
1        TCGA-02-0003       1.0    144.0        1.0      40.0
2        TCGA-02-0004       1.0    345.0        1.0     314.0
3        TCGA-02-0006       1.0    558.0        1.0     302.0
4        TCGA-02-0007       1.0    705.0        1.0     518.0

In [15]:
embeddings = load_pickle("/data/rbg/users/ashyamal/RNA-FM-benchmarking/data/RNA_embeddings/TCGA_processed_HVG.pkl")

In [16]:
embeddings['TCGA-AB-2911']['BulkFormer_HVG_1250']

array([-3.24506253e-01, -2.60605145e+00, -5.70197761e-01, -8.76725316e-01,
        8.71399403e-01,  1.71529666e-01, -7.38718629e-01,  1.31308794e+00,
       -1.88633716e+00, -1.28142309e+00,  2.04639986e-01, -2.11778972e-02,
       -2.13997394e-01,  3.93419683e-01, -8.71468782e-02,  3.68212879e-01,
        1.31070602e+00, -7.21798092e-02, -1.01183081e+00,  1.50637671e-01,
        2.02884361e-01, -8.27679813e-01,  1.33338356e+00,  4.59863037e-01,
       -7.81250358e-01,  9.27442670e-01, -5.58052957e-01, -1.59003091e+00,
       -9.92460772e-02, -4.58003521e-01, -8.01043332e-01,  5.17141342e-01,
        3.88639160e-02,  3.43681037e-01,  2.47906402e-01,  3.81626368e-01,
       -7.61792839e-01, -1.44309604e+00, -5.00080490e+00, -5.90622485e-01,
       -5.67808092e-01,  2.87845910e-01, -1.12099993e+00, -2.28620574e-01,
        9.74283218e-01,  1.57670677e-01,  7.78354406e-01, -1.78540777e-02,
       -4.01572764e-01, -8.95212770e-01, -1.00125723e-01, -3.31693725e-03,
       -3.64665449e-01, -3.60370427e-01,  8.17539871e-01, -6.79880679e-01,
       -1.72497630e-02, -1.94706321e-01,  2.49103103e-02,  1.22228354e-01,
       -1.14077844e-01,  6.43370688e-01,  4.93680865e-01, -9.52516913e-01,
        9.25363481e-01,  1.12369083e-01,  1.68866009e-01,  2.25973949e-01,
        7.44242892e-02, -1.15416336e+00,  6.57312036e-01, -9.88419712e-01,
        1.42627239e-01, -6.61871016e-01,  2.76625061e+00,  9.56519842e-01,
       -5.88677406e-01,  2.05723643e+00, -2.15503618e-01,  1.33412433e+00,
       -1.04858533e-01,  9.20216799e-01, -1.02769458e+00,  1.55706429e+00,
        4.62112099e-01,  1.02521741e+00,  4.56111617e-02,  4.16821629e-01,
       -9.24033672e-02, -1.87864348e-01,  3.12060094e+00,  4.98338342e-01,
        5.37965894e-01, -9.99597073e-01, -5.44571221e-01,  8.93507719e-01,
       -1.27200047e-02,  7.29114830e-01,  3.90097916e-01,  1.44952393e+00,
        2.51619313e-02, -9.93074715e-01, -1.07872355e+00, -5.04265726e-01,
        2.96820194e-01, -3.38858336e-01, -1.01999545e+00, -4.71285045e-01,
        1.35181416e-02,  1.73571599e+00, -6.06816649e-01, -1.80151165e-01,
        1.01957166e+00, -4.33028013e-01,  1.97177792e+00, -4.79404479e-01,
        2.84655482e-01, -5.78668773e-01, -1.32939100e+00, -7.26227835e-02,
       -2.04700518e+00,  4.74000096e-01, -5.25517941e-01,  1.29263446e-01,
        1.01796532e+00,  1.99927032e-01, -1.21969238e-01, -4.34767276e-01,
       -1.05905615e-01, -9.91866410e-01, -4.56401557e-01, -8.39233696e-02,
       -3.75920564e-01,  1.79309174e-01, -1.95114344e-01, -3.57107282e-01,
        2.31436819e-01,  1.07090521e+00,  1.00999856e+00, -1.60935357e-01,
       -6.00575745e-01, -2.86262900e-01, -6.76883817e-01, -4.04932171e-01,
        6.82922184e-01, -1.30774211e-02, -8.03714871e-01, -9.10593152e-01,
        9.48901176e-01, -6.37796760e-01, -4.77991909e-01, -2.04030201e-01,
       -1.73533291e-01, -3.48166451e-02,  2.83142217e-02, -4.06034410e-01,
        7.00925216e-02, -8.75219047e-01, -8.08302462e-01,  2.01946878e+00,
        4.89742272e-02,  1.87847579e+00, -4.27658677e-01, -1.26718462e+00,
       -5.93355238e-01, -7.64994696e-02,  5.37843108e-01, -3.05335373e-01,
        7.19256759e-01, -7.04896808e-01,  4.29290086e-01, -1.77097249e+00,
       -8.40178430e-01,  3.18132639e-01, -1.08401847e+00, -1.25626996e-01,
        4.67702523e-02, -4.06145096e-01,  9.46491420e-01, -1.94891059e+00,
        1.22647934e-01, -3.90161037e-01, -7.70347834e-01,  1.03372586e+00,
       -1.84993371e-01,  1.86275160e+00,  2.95270324e-01, -1.06895149e+00,
        1.30389497e-01,  5.25586486e-01, -6.20599806e-01,  5.98659590e-02,
       -4.85963300e-02,  4.48530465e-01,  1.02108884e+00, -5.91944993e-01,
        7.52133608e-01, -6.75338328e-01, -1.11988500e-01, -5.79281449e-01,
        1.00001078e-02,  1.28281379e+00, -3.82848442e-01,  5.77995479e-01,
       -1.83425218e-01, -5.38342781e-02,  5.21825969e-01,  2.53286600e-01,
       -1.75256208e-01,  2.14018658e-01,  5.14190674e-01, -5.75268865e-01,
        1.05414057e+00, -6.72162175e-01, -8.65839243e-01,  5.63012183e-01,
        1.31589854e+00, -4.14197117e-01,  8.70716572e-01,  1.20221841e+00,
       -1.49656844e+00,  1.78159261e+00, -1.54071116e+00, -9.27180886e-01,
        1.01526821e+00,  7.15774596e-01, -6.92651927e-01,  7.92631626e-01,
        8.79490733e-01, -9.69189763e-01, -4.08206761e-01,  5.43986380e-01,
        1.07625306e+00,  6.41057432e-01, -4.45132017e-01,  1.01139456e-01,
        1.42354929e+00, -1.32217860e+00,  2.18403563e-01, -5.79716921e-01,
        9.48987603e-01,  2.58113950e-01, -7.51301825e-01, -7.10499108e-01,
       -2.94608742e-01, -1.82944402e-01, -6.24994040e-01,  5.23688316e-01,
       -3.57834935e-01,  2.07213715e-01, -5.70880622e-02,  2.16995883e+00,
        6.58436716e-02,  4.71845984e-01, -1.71745741e+00, -2.91078866e-01,
        1.17695928e+00, -1.37259054e+00, -8.36797178e-01, -3.81654500e-05,
       -4.61080223e-01, -1.92424119e-01, -2.21420586e-01, -6.87770396e-02,
       -1.09347844e+00,  8.05531681e-01, -1.70766366e+00, -6.24039412e-01,
       -5.27417362e-01,  2.80365467e-01, -2.06623173e+00, -1.64711285e+00,
       -7.26068020e-01, -4.87932324e-01, -5.27018309e-01, -6.84776783e-01,
        1.97854555e+00, -4.42833781e-01, -1.25832713e+00, -6.24042094e-01,
        3.03186059e-01,  1.63891334e-02,  2.15860128e-01, -6.94968551e-02,
       -1.64725021e-01, -5.23911357e-01, -1.95382461e-01,  1.21933925e+00,
       -4.84562367e-01, -9.31478322e-01, -4.35734570e-01,  1.09202731e+00,
       -1.83726922e-01, -5.78480244e-01, -1.45701289e-01,  6.29970849e-01,
       -7.77561069e-01,  2.25007787e-01,  2.56566226e-01,  5.62207401e-01,
       -7.79859543e-01, -6.11246407e-01, -5.15976846e-01,  1.24166214e+00,
       -2.62609512e-01, -2.97966957e-01, -1.41584253e+00, -2.38730788e-01,
       -9.56684589e-01,  4.46587741e-01,  9.93605196e-01,  1.81321502e-01,
        8.45763981e-01, -2.87050605e-01,  4.82311510e-02,  6.25827610e-01,
        1.01870373e-01, -4.77463335e-01, -9.23369646e-01, -1.26042545e+00,
       -1.87608957e-01,  9.78204668e-01, -8.65398347e-01, -1.53837883e+00,
        1.87782034e-01,  2.07921767e+00,  2.96175182e-01, -2.28650361e-01,
       -4.21545446e-01,  9.20586526e-01,  1.16491938e+00,  2.56571770e-01,
        1.66462883e-01,  4.72551018e-01, -2.08977327e-01, -7.79558301e-01,
       -2.13426486e-01, -1.47274494e-01, -4.94552702e-02,  2.80122668e-01,
        6.52617097e-01, -1.75738668e+00,  2.06998810e-01, -6.48852706e-01,
       -1.06327593e+00,  6.91274047e-01,  4.14778382e-01,  3.04343522e-01,
       -2.57937551e-01, -2.22013574e-02,  2.27385491e-01, -1.87700784e+00,
       -2.40495396e+00,  7.41327032e-02, -5.23180664e-01,  1.22332323e+00,
       -2.85192847e-01,  1.37819302e+00,  5.51748395e-01, -1.58609822e-01,
        3.12761664e-01,  1.55812591e-01, -4.16906923e-01, -2.46297400e-02,
        2.24756956e+00, -2.72164285e-01,  6.80066884e-01, -3.99469137e-01,
       -3.68362099e-01, -6.69248328e-02,  1.06774652e+00,  7.93565452e-01,
       -6.12564802e-01,  6.84721172e-01, -2.07493797e-01,  5.31265318e-01,
       -9.92635965e-01, -1.82393491e-01,  4.09116112e-02, -9.54716921e-01,
       -1.19170928e+00,  1.92713067e-01,  3.30222249e-01, -7.73480237e-02,
        9.57642555e-01, -2.30733715e-02, -1.79484391e+00, -3.48663598e-01,
        1.37997746e+00,  6.54069662e-01, -2.85714269e-01,  2.80845463e-01,
        6.96979761e-01,  1.55846417e-01,  6.58721328e-02,  3.69180650e-01,
       -4.05917853e-01,  1.19126070e+00,  2.61320919e-01, -2.69750357e-01,
        1.96371257e-01, -6.86319053e-01, -1.86317675e-02,  2.77739465e-01,
       -4.29649800e-01, -9.88145292e-01, -7.85926938e-01,  7.45135725e-01,
        8.66276741e-01,  1.92391431e+00, -5.26352525e-01,  4.54324216e-01,
       -4.86652821e-01,  7.41416872e-01, -9.94560644e-02, -2.96470791e-01,
       -4.08888422e-02,  1.03290963e+00, -2.17119232e-01,  2.56946653e-01,
       -4.31326598e-01, -5.62511832e-02,  4.65822935e-01,  6.76320791e-02,
        4.34773237e-01,  3.75040203e-01,  1.71308577e-01,  2.05532853e-02,
        1.09800182e-01,  1.70170348e-02,  1.52282834e-01,  5.86478889e-01,
       -2.13237837e-01, -2.29590744e-01, -2.52740890e-01, -2.84269714e+00,
        1.31301939e+00, -5.02047062e-01, -6.57291234e-01, -7.61488229e-02,
       -7.68490359e-02, -6.95111573e-01,  6.03051543e-01, -6.52571917e-01,
       -7.88180232e-02, -8.75224829e-01, -6.92113042e-01, -2.31210589e-01,
        3.78261209e-01,  3.68070990e-01,  2.00146243e-01,  1.01338744e+00,
        1.36465907e-01,  1.11729360e+00, -3.62458259e-01,  3.93029809e-01,
       -6.47652507e-01, -8.76984060e-01, -1.33238673e-01,  4.73373443e-01,
       -5.86193144e-01,  3.98508348e-02, -3.78598645e-02,  9.41446602e-01,
        1.15862274e+00,  1.12973022e+00, -4.81965244e-01,  2.35988498e-01,
        1.59635520e+00, -2.10595942e+00,  7.90864706e-01,  1.17877269e+00,
        6.82803988e-01, -2.50098318e-01, -4.82111633e-01,  4.73582417e-01,
       -2.72902817e-01,  7.11230695e-01, -3.31105262e-01, -1.61542726e+00,
       -1.46542981e-01,  7.10232079e-01, -6.23017609e-01,  4.41902012e-01,
       -8.34426761e-01, -7.21600592e-01,  8.62376094e-01, -4.41501513e-02,
       -3.40079404e-02, -4.73326101e-04,  1.29333329e+00, -4.33701128e-01,
        3.99527997e-01, -1.69495058e+00,  4.41192627e-01,  2.53501087e-01,
       -1.30569565e+00, -2.49398537e-02, -5.76163292e-01,  4.67447907e-01,
        8.21202934e-01,  8.64028931e-01,  1.10432017e+00, -1.38410854e+00,
        9.66343939e-01, -6.99762106e-01,  6.81840301e-01,  6.90000594e-01,
       -1.13240518e-01, -3.03824425e-01, -8.28161061e-01,  5.18501759e-01,
        1.43343675e+00,  1.47912514e+00,  3.08717877e-01,  6.24929331e-02,
       -4.69451517e-01, -4.33537692e-01,  6.61326870e-02, -2.34035894e-01,
        5.20834506e-01, -3.22522402e-01, -7.01734126e-01,  3.32354456e-01,
        2.06841692e-01,  1.47788298e+00, -2.24319309e-01,  2.37725210e+00,
        1.62643516e+00, -8.13564122e-01,  1.12238681e+00, -4.97779101e-01,
       -3.71789992e-01, -2.36192062e-01,  1.40145168e-01,  3.10390648e-02,
        7.86918998e-01,  3.34277183e-01,  8.01085234e-02,  1.02931249e+00,
       -1.62108764e-01,  2.51095444e-01, -5.60152642e-02,  1.90536714e+00,
       -1.68132111e-01,  1.54231071e+00, -1.48921013e+00,  1.00841427e+00,
        1.25079393e+00, -3.31306338e-01, -1.83925045e+00, -2.59089202e-01,
       -3.31362933e-01,  1.74828351e-01, -1.81906271e+00, -5.85421205e-01,
       -5.22226751e-01, -1.00964129e-01, -3.66384149e-01,  4.18772399e-01,
        1.28151238e-01,  3.27883542e-01,  5.11923313e-01,  6.27266526e-01,
       -2.47486550e-02,  2.42082500e+00, -9.92128626e-03,  5.44694722e-01,
       -2.29377604e+00,  1.02883160e+00,  4.29433584e-01, -9.52018857e-01,
        2.08011493e-01,  1.15299058e+00,  1.47984505e-01, -4.16794926e-01,
        2.10121781e-01, -8.45916510e-01,  7.23197877e-01, -7.99099147e-01,
       -1.54506159e+00, -2.14528814e-01,  3.96749318e-01,  2.68523049e+00,
        5.04417002e-01, -9.64179218e-01, -3.78623866e-02,  1.41743696e+00,
        9.42958176e-01, -8.91323328e-01, -1.01284194e+00, -7.37182796e-01,
        4.64020222e-01, -2.53888577e-01, -1.06328636e-01, -1.29900917e-01,
        6.39250457e-01, -5.50519407e-01, -5.12082875e-01, -8.53910029e-01,
       -3.80258411e-01,  2.27978444e+00, -4.68642294e-01,  5.28511293e-02,
       -6.55635357e-01, -2.79955566e-01,  6.41876340e-01,  9.03335869e-01,
       -7.66409934e-01,  4.24525350e-01, -9.72275659e-02, -3.46558958e-01,
        2.59912200e-02,  3.87215525e-01,  1.66564107e+00,  5.64777017e-01,
       -8.28521669e-01, -2.36808494e-01,  5.14585495e-01, -9.00959492e-01,
        9.95223969e-02, -9.02536154e-01,  8.10053408e-01,  3.71373981e-01,
       -1.19162655e+00,  8.28879178e-01,  8.87700677e-01,  1.56668365e-01,
       -5.94270706e-01,  9.93867099e-01, -1.77284956e-01, -6.98373079e-01,
        5.85150599e-01,  1.39708877e+00, -5.72390556e-01,  1.15188766e+00,
       -1.43688393e+00, -3.18082511e-01,  4.20401067e-01,  2.28345454e-01],
      dtype=float32)

In [17]:
patients_with_cleaned_labels = set(survival_labels['bcr_patient_barcode'])
len(patients_with_cleaned_labels)

11160

In [18]:
patients_in_embeddings_with_PFS_labels = set()
for patient_id in embeddings.keys():
    if not any(pd.isna([embeddings[patient_id]['PFS_time'], embeddings[patient_id]['PFS_event']])):
        patients_in_embeddings_with_PFS_labels.add(patient_id)

print(f"Out of {len(embeddings)} patients in the embeddings, {len(patients_in_embeddings_with_PFS_labels)} have PFS labels.")

Out of 10478 patients in the embeddings, 10388 have PFS labels.

In [19]:
patients_in_embeddings_with_cleaned_labels = [patient for patient in patients_in_embeddings_with_PFS_labels if patient in patients_with_cleaned_labels]
len(patients_in_embeddings_with_cleaned_labels)

10388

In [20]:
# Create copy of embeddings with new labels for PFS_time and PFS_event
nan_patients = set()
new_embeddings = {}
for patient in tqdm(patients_in_embeddings_with_cleaned_labels):
    new_embeddings[patient] = embeddings[patient].copy()
    # Get the corresponding PFS_time and PFS_event from survival_labels
    pfs_time = survival_labels[survival_labels['bcr_patient_barcode'] == patient]['PFS_time'].values[0]
    pfs_event = survival_labels[survival_labels['bcr_patient_barcode'] == patient]['PFS_event'].values[0]
    os_time = survival_labels[survival_labels['bcr_patient_barcode'] == patient]['OS_time'].values[0]
    os_event = survival_labels[survival_labels['bcr_patient_barcode'] == patient]['OS_event'].values[0]
    # Update the embedding with the new labels only if the PFS label's values are not NaN
    if not any(pd.isna([pfs_time, pfs_event])):
        new_embeddings[patient]['PFS_time'] = pfs_time
        new_embeddings[patient]['PFS_event'] = pfs_event
        new_embeddings[patient]['OS_time'] = os_time
        new_embeddings[patient]['OS_event'] = os_event
    else:
        nan_patients.add(patient)

  0%|          | 0/10388 [00:00<?, ?it/s]

In [21]:
len(nan_patients)

149

In [22]:
# Ensure no NaN values in the new embeddings' PFS values
for patient in new_embeddings:
    if any(pd.isna([new_embeddings[patient]['PFS_time'], new_embeddings[patient]['PFS_event']])):
        print(f"NaN values found for patient {patient}")

In [23]:
len(new_embeddings)

10388

In [24]:
# Compute number of patients with differening PFS_time, PFS_event between the original and new embeddings
differing_patients = set()
for patient in new_embeddings:
    if (new_embeddings[patient]['PFS_time'] != embeddings[patient]['PFS_time']) or \
       (new_embeddings[patient]['PFS_event'] != embeddings[patient]['PFS_event']):
        differing_patients.add(patient)
len(differing_patients)

290

In [25]:
print(f"Number of patients with NaN cleaned values in PFS_time or PFS_event: {len(nan_patients)}")

Number of patients with NaN cleaned values in PFS_time or PFS_event: 149

In [26]:
pickle_data(new_embeddings, "/data/rbg/users/ashyamal/RNA-FM-benchmarking/data/RNA_embeddings/TCGA_processed_HVG_cleaned.pkl")